"use client"; // Add this directive at the top

import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

/*export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};*/

/*export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>{children}</body>
        </html>
    );
}*/

// src/app/layout.tsx
import {useState, useEffect} from "react";
import {Card, CardHeader, CardContent, CardTitle} from "@/components/ui/card";

export default function RootLayout({children}: { children: React.ReactNode }) {
    const [tasks, setTasks] = useState<string[]>([]);

    useEffect(() => {
        // Fetch tasks from API or backend
        fetch("http://localhost:8000/api/tasks/pending")
            .then((response) => response.json())
            .then((data) => setTasks(data)); // Assuming the API returns an array of tasks
    }, []);

    return (
        <html lang="en">
        <body className="flex">
        {/* Main content area */}
        <div className="flex-grow p-4">{children}</div>

        {/* Right side panel */}
        <div
            className="w-80 bg-gray-50 border-l border-gray-200 shadow-lg p-4 fixed top-0 right-0 h-full overflow-y-auto">
            <Card className="h-full">
                <CardHeader>
                    <CardTitle className="text-xl font-bold">Pending Tasks</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                    {tasks.length === 0 ? (
                        <p className="text-gray-500">No pending tasks</p>
                    ) : (
                        <ul className="space-y-2">
                            {tasks.map((task, index) => (
                                <li key={index} className="text-gray-800">
                                    - {task}
                                </li>
                            ))}
                        </ul>
                    )}
                </CardContent>
            </Card>
        </div>
        </body>
        </html>
    );
}
